name: 🐛 Bug Report
description: Create a bug report to help us improve Fallen-Networks CS2-RampFix
title: 'bug: '

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you have completed all of the following.
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/Fallen-Networks/CS2-RampFix/blob/main/CONTRIBUTING.md#creating-an-issue).
          required: true
        - label: I have searched for [existing issues](https://github.com/Fallen-Networks/CS2-RampFix/issues) that already report this problem, without success.
          required: true

  - type: dropdown
    id: affected-versions
    attributes:
      label: Fallen-Networks CS2-RampFix Versions
      description: Which version(s) of Fallen-Networks CS2-RampFix does this issue impact?.
      options:
        - v1.x.x
      multiple: true
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please explain the steps required to duplicate this issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Github links, Stack Overflow links, forum links, etc.
